# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chromesnap < Formula
  desc "Headless Chrome screenshot CLI and Go library"
  homepage "https://github.com/normal-coder/chromesnap"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/normal-coder/chromesnap/releases/download/v1.0.0/chromesnap_1.0.0_darwin_amd64.tar.gz"
      sha256 "eacd5e3047a7b321b352fbd801d2a1da4989f1caab39148bb87eb472bce0af1e"

      define_method(:install) do
        bin.install "chromesnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/normal-coder/chromesnap/releases/download/v1.0.0/chromesnap_1.0.0_darwin_arm64.tar.gz"
      sha256 "0b0a3a95a0d06db95bf5778fb56281b5a5363cb53feea82de6760a8b2e57179c"

      define_method(:install) do
        bin.install "chromesnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/normal-coder/chromesnap/releases/download/v1.0.0/chromesnap_1.0.0_linux_amd64.tar.gz"
      sha256 "3e8779c9bad3ef11b8b6dceca5ced05a44b690731ed8734ff32939b6001e9660"
      define_method(:install) do
        bin.install "chromesnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/normal-coder/chromesnap/releases/download/v1.0.0/chromesnap_1.0.0_linux_arm64.tar.gz"
      sha256 "41e5e37f6a51eaa3dea7f21e4e04acf634d488778ffa6ff61f430a40370c447a"
      define_method(:install) do
        bin.install "chromesnap"
      end
    end
  end

  test do
    system "#{bin}/chromesnap version"
  end
end
