# This file was generated by GoReleaser. DO NOT EDIT.
cask "chromesnap" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "80a71bf9155520b529e617a744bcc36d8b8fa1d3d447708def5f4e7ab6fb007a"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "433a4e5d47051e4438c35d68464d750436621a1e775795962f97ff6347b10591"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d76e3d4429d68d42f11cfa70976a970628373405c264c204c2826b563896a0f"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "3c754a79a68fdbfbe8e636dc450fab0249f0ec8094f35763b1efbd92dd5417c0"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  name "chromesnap"
  desc "Headless Chrome screenshot CLI and Go library"
  homepage "https://github.com/normal-coder/chromesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chromesnap"

  # No zap stanza required

end
