# This file was generated by GoReleaser. DO NOT EDIT.
cask "chromesnap" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "58602c219da82a5530a5e07a7343d2f017e2476f0ee2cf4b8f8a99c74c13a8ee"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "83b58fe25903961a6fa485d1445018e96398e08257adabc316b2ad07971e4ed4"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c8b00e5273b38fc0400a50ebe43b3b2597086eca2de6b91d3bd61cc4777ff85"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "677d4bbd8529eb8a9d6eb8a7f4b2e983ba6b76a76a4f93553f4f0c414187eab4"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  name "chromesnap"
  desc "Headless Chrome screenshot CLI and Go library"
  homepage "https://github.com/normal-coder/chromesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chromesnap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chromesnap"]
    end
  end

  # No zap stanza required

end
