# This file was generated by GoReleaser. DO NOT EDIT.
cask "chromesnap" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "1674dca8de3d1d01636b3c648529492882f4135a0f2847d7caa725f770e12697"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "eaab24e88c5c97b6bbd48d1c9ee21db0616eaf507b26824b00366f58a6dcb28c"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4a2a50154b68951f5f6f36434c99801d9e90dfa63c6f39e4b661c97d9e71a33"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_amd64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
    on_arm do
      sha256 "db383b291a66cc2fcb32cb66d81a711eceb3132c0f941dbf52985fa9fad50662"
      url "https://github.com/normal-coder/chromesnap/releases/download/v#{version}/chromesnap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/normal-coder/chromesnap"
    end
  end

  name "chromesnap"
  desc "Headless Chrome screenshot CLI and Go library"
  homepage "https://github.com/normal-coder/chromesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chromesnap"

  # No zap stanza required

end
