# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmctl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "405fefe370ee387eab4628e0a37c3b24f8bd8918084819e0fc0e8043179531d2"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "936d95b8c37c540bf6134ee51b216676aca5e18729c37ef7a1ca326fc9a83174"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0c53276b6bb2a8860f47933f434e3c326e8faa94c525ddab268adff4659cdf76"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a39740e6cc245c7872b75972113d7fe220e4e7fa98122a414fdb2a7796713377"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vmctl"
  desc "VMware virtual machine control CLI inspired by prlctl, with vmrun and vSphere backends"
  homepage "https://github.com/normal-coder/vmctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmctl"]
    end
  end

  # No zap stanza required
end
