# This file was generated by GoReleaser. DO NOT EDIT.
cask "vmctl" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "830103bc84ce6bd0f03ddcec2b4b2706f603e36499f3963288fd0ba0ebfdd7b2"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "57614a87ef80939da39bbab8ac6a1ae7bcebd9e10be58410949b5afdfebf70ab"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d21a8b9a47a499c59dde8008b664a5db1187968fca7b8a5ed2ef50ccba404208"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3def5d6b72657d14b975e28a3aa38138d57d5e50f771d0587fd9cc156a3ada2f"
      url "https://github.com/normal-coder/vmctl/releases/download/v#{version}/vmctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vmctl"
  desc "VMware virtual machine control CLI inspired by prlctl, with vmrun and vSphere backends"
  homepage "https://github.com/normal-coder/vmctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vmctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vmctl"]
    end
  end

  # No zap stanza required
end
